# src/investigation_agent_platform/domain/reference/__init__.py
"""Reference-document domain (Part 11.6)."""

from investigation_agent_platform.domain.reference.documents import (
    MAX_INDEX_BATCHES_PER_RUN,
    MAX_REFERENCE_CHUNK_CHARS,
    MAX_REFERENCE_CHUNKS_PER_FILE,
    MAX_REFERENCE_CHUNKS_PER_RUN,
    MAX_REFERENCE_FILE_BYTES,
    MAX_REFERENCE_FILES,
    MAX_REFERENCE_SOURCES,
    REFERENCE_DOC_CONTRACT_VERSION,
    REFERENCE_EMBEDDING_DIMS,
    REINDEX_BATCH_SIZE,
    ChunkLifecycle,
    FetchedFile,
    GenerationStatus,
    GitSourceSpec,
    IndexGeneration,
    IndexRunSummary,
    IndexStatus,
    LocalPathSourceSpec,
    ReferenceDocumentChunk,
    ReferenceDocumentSource,
    ReferenceSearchHit,
    ReferenceSourceKind,
    S3SourceSpec,
)

__all__ = [
    "MAX_INDEX_BATCHES_PER_RUN",
    "MAX_REFERENCE_CHUNKS_PER_FILE",
    "MAX_REFERENCE_CHUNKS_PER_RUN",
    "MAX_REFERENCE_CHUNK_CHARS",
    "MAX_REFERENCE_FILES",
    "MAX_REFERENCE_FILE_BYTES",
    "MAX_REFERENCE_SOURCES",
    "REFERENCE_DOC_CONTRACT_VERSION",
    "REFERENCE_EMBEDDING_DIMS",
    "REINDEX_BATCH_SIZE",
    "ChunkLifecycle",
    "FetchedFile",
    "GenerationStatus",
    "GitSourceSpec",
    "IndexGeneration",
    "IndexRunSummary",
    "IndexStatus",
    "LocalPathSourceSpec",
    "ReferenceDocumentChunk",
    "ReferenceDocumentSource",
    "ReferenceSearchHit",
    "ReferenceSourceKind",
    "S3SourceSpec",
]
